# Seminar 4

Se aruncă o monedă de $n=10, 20, 300$ de ori. Probabilitatea ca stema să apară de $k=5, 14, 145$ de ori. 

In [150]:
import numpy as np
from scipy.special import comb
# from itertools import combinations_with_replacement
from itertools import product

## varianta 1

In [3]:
def moneda():
    # genereaza numere aleatoare
    if np.random.rand()<0.5:
        return 1 # 1 = Stema
    else:
        return 0 # 0 = Marca

In [16]:
moneda()

0

In [4]:
def moneda():
    return 1 if np.random.rand()>0.5 else 0

In [6]:
moneda()

1

In [15]:
dictionar={0: 'M', 1:'S'}

In [8]:
dictionar[moneda()]

'M'

In [5]:
n = 10
stema = 0
for i in range(n):
    if moneda()==1:
        stema+=1
print(stema)

4


In [6]:
n = 10
stema = 0
for i in range(n):
    if moneda():
        stema+=1
print(stema)

6


In [7]:
def moneda_repetata(n):
    stema = 0
    for i in range(n):
        stema+=moneda()
    return stema/n

In [30]:
moneda_repetata(100)

0.58

In [8]:
def moneda_repetata_k(n, k):
    stema = 0
    for i in range(n):
        stema+=moneda()
    return 1 if stema==k else 0

In [21]:
moneda_repetata_k(10, 5)

0

In [22]:
nr_repetitii=100000

In [9]:
nr_reusite=0
n=10
k=5
for repetari in range(nr_repetitii):
    nr_reusite+=moneda_repetata_k(n, k)
print(nr_reusite/nr_repetitii)

0.24534


Ctrl + "[" - align to left. Analog for "]"

Probabilitatea teoretica: $P(X_n^k)=C_n^k p^k q^{n-k}$ (schema binomiala)

In [10]:
def probabilitate_teoretica_moneda(p, n, k):
    return comb(n,k)*p**k*(1-p)**(n-k)

In [25]:
probabilitate_teoretica_moneda(0.5, 10, 5)

0.24609375

In [12]:
%%timeit
N=[10, 20, 300]
K=[5, 14, 145]
nr_repetitii=100000
for n, k in zip(N, K):
    nr_reusite=0
    for repetari in range(nr_repetitii):
        nr_reusite+=moneda_repetata_k(n, k)
    print(f'n={n}, k={k}, teoretic: {probabilitate_teoretica_moneda(0.5, n, k)}, simulare: {nr_reusite/nr_repetitii}')

n=10, k=5, teoretic: 0.24609375, simulare: 0.24509
n=20, k=14, teoretic: 0.03696441650390625, simulare: 0.03732
n=300, k=145, teoretic: 0.038981861224294305, simulare: 0.0396
n=10, k=5, teoretic: 0.24609375, simulare: 0.24765
n=20, k=14, teoretic: 0.03696441650390625, simulare: 0.03635
n=300, k=145, teoretic: 0.038981861224294305, simulare: 0.03845
n=10, k=5, teoretic: 0.24609375, simulare: 0.24599
n=20, k=14, teoretic: 0.03696441650390625, simulare: 0.037
n=300, k=145, teoretic: 0.038981861224294305, simulare: 0.03858
n=10, k=5, teoretic: 0.24609375, simulare: 0.24435
n=20, k=14, teoretic: 0.03696441650390625, simulare: 0.0375
n=300, k=145, teoretic: 0.038981861224294305, simulare: 0.03938
n=10, k=5, teoretic: 0.24609375, simulare: 0.24858
n=20, k=14, teoretic: 0.03696441650390625, simulare: 0.03798
n=300, k=145, teoretic: 0.038981861224294305, simulare: 0.03852
n=10, k=5, teoretic: 0.24609375, simulare: 0.24589
n=20, k=14, teoretic: 0.03696441650390625, simulare: 0.03659
n=300, k=145

## varianta 2

In [35]:
n=10
k=5

In [ ]:
nr_repetitii=1000000
monede=np.random.rand(nr_repetitii, n)

In [ ]:
monede

In [38]:
steme = monede>0.5

In [39]:
steme

array([[ True,  True, False,  True,  True, False,  True, False, False,
         True],
       [False,  True,  True,  True,  True, False, False, False, False,
         True],
       [ True,  True,  True, False, False, False,  True,  True,  True,
        False],
       [ True, False,  True,  True, False,  True,  True, False, False,
         True],
       [ True, False, False, False,  True,  True,  True, False, False,
        False],
       [False, False,  True,  True,  True, False,  True, False, False,
         True],
       [ True, False,  True,  True, False,  True, False,  True,  True,
        False],
       [False,  True,  True, False, False,  True,  True, False,  True,
        False],
       [ True,  True, False, False,  True, False, False, False,  True,
        False],
       [ True, False,  True, False,  True,  True, False, False, False,
        False],
       [ True,  True, False, False,  True,  True, False,  True, False,
        False],
       [ True,  True,  True, False, False, 

In [40]:
cate_steme = np.sum(steme, axis = 1)

In [41]:
cate_steme

array([6, 5, 6, 6, 4, 5, 6, 5, 4, 4, 5, 7, 5, 6, 3, 6, 3, 6, 5, 5])

In [42]:
numar = cate_steme==k

In [43]:
numar

array([False,  True, False, False, False,  True, False,  True, False,
       False,  True, False,  True, False, False, False, False, False,
        True,  True])

In [44]:
numar = np.sum(cate_steme==k)

In [45]:
numar

7

In [46]:
numar/nr_repetitii

0.35

In [13]:
N=[10, 20, 300]
K=[5, 14, 145]
nr_repetitii=100000
for n, k in zip(N, K):
    monede=np.random.rand(nr_repetitii, n)
    steme = monede>0.5
    cate_steme = np.sum(steme, axis = 1)
    numar = np.sum(cate_steme==k)
    print(f'n={n}, k={k}, teoretic: {probabilitate_teoretica_moneda(0.5, n, k)}, simulare: {numar/nr_repetitii}')

n=10, k=5, teoretic: 0.24609375, simulare: 0.24714
n=20, k=14, teoretic: 0.03696441650390625, simulare: 0.0375
n=300, k=145, teoretic: 0.038981861224294305, simulare: 0.03905


In [15]:
%%timeit
N=[10, 20, 300]
K=[5, 14, 145]
nr_repetitii=100000
for n, k in zip(N, K):
    # monede=np.random.rand(nr_repetitii, n)
    # steme = monede>0.5
    # cate_steme = np.sum(steme, axis = 1)
    numar = np.sum(np.sum(np.random.rand(nr_repetitii, n)>0.5, axis=1)==k)
    print(f'n={n}, k={k}, teoretic: {probabilitate_teoretica_moneda(0.5, n, k)}, simulare: {numar/nr_repetitii}')

n=10, k=5, teoretic: 0.24609375, simulare: 0.24506
n=20, k=14, teoretic: 0.03696441650390625, simulare: 0.03747
n=300, k=145, teoretic: 0.038981861224294305, simulare: 0.03909
n=10, k=5, teoretic: 0.24609375, simulare: 0.24521
n=20, k=14, teoretic: 0.03696441650390625, simulare: 0.03756
n=300, k=145, teoretic: 0.038981861224294305, simulare: 0.03825
n=10, k=5, teoretic: 0.24609375, simulare: 0.24829
n=20, k=14, teoretic: 0.03696441650390625, simulare: 0.03746
n=300, k=145, teoretic: 0.038981861224294305, simulare: 0.04002
n=10, k=5, teoretic: 0.24609375, simulare: 0.24373
n=20, k=14, teoretic: 0.03696441650390625, simulare: 0.03678
n=300, k=145, teoretic: 0.038981861224294305, simulare: 0.03913
n=10, k=5, teoretic: 0.24609375, simulare: 0.24707
n=20, k=14, teoretic: 0.03696441650390625, simulare: 0.03696
n=300, k=145, teoretic: 0.038981861224294305, simulare: 0.03802
n=10, k=5, teoretic: 0.24609375, simulare: 0.24512
n=20, k=14, teoretic: 0.03696441650390625, simulare: 0.0368
n=300, k=

## muncă individuală

Se aruncă o monedă de $n=10, 20, 300$ de ori. Probabilitatea ca stema să apară **cel putin** de $k=5, 14, 145$ de ori. 

Formula de calcul: $P(X)=P(X_n^k)+P(X_n^{k+1})+...+P(X_n^n)$

In [6]:
def probabilitate_teoretica_moneda(p, n, k):
    return comb(n,k)*p**k*(1-p)**(n-k)

In [7]:
def probabilitate_teoretica_moneda_conditie(p, n, k):
    probabilitate = 0
    for i in range(k, n+1):
        probabilitate = probabilitate + probabilitate_teoretica_moneda(p,n,i)
    return probabilitate

In [11]:
N = [10, 20, 300]
K = [5, 14, 145]
nr_repetitii = 100000
for n, k in zip(N, K):
    monede = np.random.rand(nr_repetitii, n)
    steme = monede > 0.5
    cate_steme = np.sum(steme, axis = 1)
    numar = np.sum(cate_steme>=k)
    print(f'n={n}, k={k}, teoretic: {probabilitate_teoretica_moneda_conditie(0.5, n, k)}, simulare: {numar/nr_repetitii}')

n=10, k=5, teoretic: 0.623046875, simulare: 0.62213
n=20, k=14, teoretic: 0.057659149169921875, simulare: 0.05601
n=300, k=145, teoretic: 0.7372790022882302, simulare: 0.7377


## temă

Se aruncă o un zar de 3 ori.  
1. Care e probabilitatea ca suma fețelor să fie 15?

**Rezolvare clasică:**    
Cazuri posibile = $6^3=216$.  
Cazuri favorabile (formula permutărilor cu repetiție):  
  
$P_R(n)=\frac{n!}{f(1)!f(2)!f(3)!...f(n)!}$ , unde f(i) este frecvența (numărul de apariții al) numărului i în permutare.  
  
(3,6,6) : $\frac{3!}{2!}=\frac{6}{2}=3$  
(4,5,6) : $3!=6$  
(5,5,5) : $\frac{3!}{3!}=1$  
Așadar, cazuri favorabile = $3+6+1=10$  
Notăm **A** - evenimentul în care suma fețelor este 15. $P(A)=\frac{cazuri favorabile}{cazuri posibile}=\frac{10}{216}=0.0462$

In [216]:
total_rolls = 3
sum_dice_rolls = 15
possible_cases = pow(6, total_rolls)
def count_dice_rolls_sum():
    favourable_cases = 0
    C = []
    for number in product(list(range(1, 7)), repeat=3):
        C.append(number)
    sum_of_elements = np.sum(C, axis = 1)
    for i in sum_of_elements:
        if i==15:
            favourable_cases+=1
    print('Number of possible cases:', possible_cases) 
    print('Number of favourable cases:', favourable_cases) 
    return favourable_cases/possible_cases

In [217]:
count_dice_rolls_sum()

Number of possible cases: 216
Number of favourable cases: 10


0.046296296296296294

2. Care e probabilitatea ca suma fețelor să fie cel puțin 15?

(3,6,6) : $\frac{3!}{2!}=\frac{6}{2}=3$  
(4,5,6) : $3!=6$  
(5,5,5) : $\frac{3!}{3!}=1$  
(5,5,6) : $\frac{3!}{2!}=3$  
(6,6,4) : $\frac{3!}{2!}=3$
(6,6,5) : $\frac{3!}{2!}=3$  
(6,6,6) : $\frac{3!}{3!}=1$  
Așadar, cazuri favorabile = $3+6+1+3+3+3+1=20$  
Notăm **B** - evenimentul în care suma fețelor este **cel puțin** 15. $P(B)=\frac{cazuri favorabile}{cazuri posibile}=\frac{17}{216}=0.0925$

In [218]:
total_rolls = 3
sum_dice_rolls = 15
possible_cases = pow(6, total_rolls)
def count_dice_rolls_sum_atleast():
    favourable_cases = 0
    C = []
    for number in product(list(range(1, 7)), repeat=3):
        C.append(number)
    sum_of_elements = np.sum(C, axis = 1)
    for i in sum_of_elements:
        if i<15:
            favourable_cases+=1
    print('Number of possible cases:', possible_cases) 
    print('Number of favourable cases:', favourable_cases) 
    return 1-favourable_cases/possible_cases

In [219]:
count_dice_rolls_sum_atleast()

Number of possible cases: 216
Number of favourable cases: 196


0.09259259259259256